# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/serranoltespr/setup-makefiles.sh

# qmuxd and rild
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/serranoltespr/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/serranoltespr/proprietary/lib/libril.so:system/lib/libril.so

# libsec-ril.so
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/serranoltespr/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/serranoltespr/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so

# libsecnativefeature.so
# libqcci_legacy.so
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so

# libqmi.so
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/lib/libdsutils.so:system/lib/libdsutils.so

# libqmiservices.so
# libidl.so
# libdiag.so
# libril-qcril-hook-oem.so
# libqmi_client_qmux.so
# libdsutils.so

# rmt_storage
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so

# libqmi_common_so.so
# liqmi_csi.so
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so

# libqmi_encdec.so

# qseecomd
PRODUCT_COPY_FILES += \
    vendor/samsung/serranoltespr/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/serranoltespr/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/serranoltespr/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so

# libQSEEComAPI.so
# libdrmfs.so
